const ROOT_ACTION = 'SALARIES';

export const SALARIES_DELETED = `${ROOT_ACTION}.DELETED`;
export const SALARIES_DELETED_SUCCEEDED = `${ROOT_ACTION}.DELETED_SUCCEEDED`;
export const SALARIES_FETCHED = `${ROOT_ACTION}.FETCHED`;
export const SALARIES_FETCHED_SUCCEEDED = `${ROOT_ACTION}.FETCHED_SUCCEEDED`;
